"use client"

import * as React from "react"
import { OverviewTab } from "./tabs/overview-tab"
import { EmptyState } from "@/components/empty-state"
import { FolderKanban, Route, Blocks, Scale, Bot, BookOpen, AlertTriangle } from "lucide-react"
import { mockProjectTasks, mockProjectGoals, mockProjectDecisions, mockProjectAgentRuns } from "../../_components/mock-projects"
import type { Project } from "@/types"

export function ProjectTabs({ project }: { project: Project }) {
  const [activeTab, setActiveTab] = React.useState("overview")
  const tabs = ["overview", "roadmap", "tasks", "architecture", "decisions", "agent_runs", "playbooks", "risks"]

  return (
    <div className="flex flex-col gap-6">
      <div className="flex overflow-x-auto border-b hide-scrollbar">
        <div className="flex space-x-1 min-w-max">
           {tabs.map(tab => (
             <button
               key={tab}
               onClick={() => setActiveTab(tab)}
               className={`px-4 py-2.5 text-sm font-bold capitalize transition-colors border-b-2 whitespace-nowrap ${
                 activeTab === tab 
                   ? "border-primary text-primary" 
                   : "border-transparent text-muted-foreground hover:text-foreground hover:bg-muted/30"
               }`}
             >
               {tab.replace("_", " ")}
             </button>
           ))}
        </div>
      </div>
      
      <div className="pt-2">
         {activeTab === "overview" && (
           <OverviewTab 
              project={project} 
              tasks={mockProjectTasks} 
              goals={mockProjectGoals} 
              decisions={mockProjectDecisions}
              agentRuns={mockProjectAgentRuns}
           />
         )}
         {activeTab === "roadmap" && <EmptyState icon={Route} title="Project Roadmap" description="Define phases and milestones to map out execution." />}
         {activeTab === "tasks" && <EmptyState icon={FolderKanban} title="Project Tasks" description="Kanban and list tracking for implementation." />}
         {activeTab === "architecture" && <EmptyState icon={Blocks} title="Architecture" description="System design, schemas, and technical context." />}
         {activeTab === "decisions" && <EmptyState icon={Scale} title="Project Decisions" description="Track technical and product decisions affecting this build." />}
         {activeTab === "agent_runs" && <EmptyState icon={Bot} title="Agent Runs" description="Outputs generated by agents for this specific project." />}
         {activeTab === "playbooks" && <EmptyState icon={BookOpen} title="Playbooks" description="Linked reusable workflows running in this project." />}
         {activeTab === "risks" && <EmptyState icon={AlertTriangle} title="Risk Register" description="Track and mitigate active threats to this mission." />}
      </div>
    </div>
  )
}
