import type { Decision } from "@/types";

export const mockDecisions: Decision[] = [
  {
    id: "d1",
    userId: "user1",
    projectId: "p1",
    title: "Use Firebase Auth over Supabase",
    context: "Needed an auth solution that integrates tightly with Firestore security rules and supports custom claims for role-based access.",
    optionsConsidered: ["Firebase Auth", "Supabase Auth", "Auth0", "Custom JWT"],
    chosenOption: "Firebase Auth",
    rationale: "Native integration with Firestore security rules, lower overhead for single-developer operation, and generous free tier.",
    tradeoffs: "Less flexibility in custom token handling vs Auth0. Migration complexity if moving away from Firebase ecosystem later.",
    risks: "Vendor lock-in to Google Cloud. Limited customization of auth flows compared to Auth0.",
    reviewDate: Date.now() + 86400000 * 30,
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 15,
  },
  {
    id: "d2",
    userId: "user1",
    projectId: "p1",
    title: "Tailwind CSS over CSS-in-JS",
    context: "Choosing a styling approach for the frontend that supports rapid development and maintains consistency across the application.",
    optionsConsidered: ["Tailwind CSS", "Styled-components", "CSS Modules", "Vanilla CSS"],
    chosenOption: "Tailwind CSS",
    rationale: "Fastest iteration speed. Excellent developer experience with IntelliSense. Built-in responsive design utilities. Strong ecosystem with shadcn/ui.",
    tradeoffs: "HTML can become verbose with many utility classes. Requires learning utility-first paradigm.",
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000 * 14,
  },
  {
    id: "d3",
    userId: "user1",
    projectId: "p1",
    title: "Single-user ownership model for V1",
    context: "Deciding whether V1 should support multi-user/team access or focus on single-user personal operating system model.",
    optionsConsidered: ["Single user", "Multi-user with roles", "Team workspaces"],
    chosenOption: "Single user",
    rationale: "Keeps V1 simple and focused on personal utility. Security rules are straightforward. Can add multi-user later without major refactor.",
    tradeoffs: "Cannot onboard team members or clients in V1. May need significant auth changes for multi-user support.",
    risks: "Users expecting team features may churn. Migration path to multi-user needs careful planning.",
    reviewDate: Date.now() + 86400000 * 60,
    createdAt: Date.now() - 86400000 * 12,
    updatedAt: Date.now() - 86400000 * 12,
  },
  {
    id: "d4",
    userId: "user1",
    projectId: "p1",
    title: "Next.js App Router over Pages Router",
    context: "Choosing the routing paradigm for the frontend framework. App Router is newer but has breaking changes.",
    optionsConsidered: ["App Router", "Pages Router", "Remix", "Vite + React Router"],
    chosenOption: "App Router",
    rationale: "Future-proof with React Server Components support. Better layout and loading state patterns. Recommended by Next.js team for new projects.",
    tradeoffs: "Steeper learning curve. Some ecosystem libraries not yet compatible. Documentation gaps in edge cases.",
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: "d5",
    userId: "user1",
    projectId: "p2",
    title: "Fixed pricing over hourly for Acme project",
    context: "Client asked for hourly rate. Need to decide pricing model that protects margins while meeting client expectations.",
    optionsConsidered: ["Hourly rate €75/hr", "Fixed price €9,500", "Retainer model", "Value-based tiered pricing"],
    chosenOption: "Fixed price €9,500",
    rationale: "Protects against scope creep by defining clear deliverables. Client prefers predictable budget. Higher effective hourly rate if delivered efficiently.",
    tradeoffs: "Risk of underestimating scope. Less flexibility to add features mid-project.",
    risks: "Client may request out-of-scope changes. Need strong change request process.",
    reviewDate: Date.now() + 86400000 * 14,
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "d6",
    userId: "user1",
    title: "Skip complex vector/RAG auth in V1",
    context: "Considering whether to implement vector database and RAG retrieval for the agent memory system in V1.",
    optionsConsidered: ["Pinecone + RAG", "Firebase vector extension", "Simple keyword search", "Skip for V1"],
    chosenOption: "Skip for V1",
    rationale: "Not core to the V1 value proposition. Simple keyword search on typed memory objects is sufficient. Can add vector search layer later.",
    tradeoffs: "Agent memory recall will be less intelligent. Keyword search may miss semantic connections.",
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 7,
  },
];
