import type { Lead, Proposal, ServiceTemplate } from "@/types";

export const mockLeads: Lead[] = [
  {
    id: "l1",
    userId: "user1",
    businessName: "Acme Wellness Studio",
    contactName: "Sarah Chen",
    niche: "Healthcare",
    source: "LinkedIn",
    painPoint: "No online booking or patient tracking system. Losing clients to competitors with better tech.",
    urgency: "high",
    budgetSignal: "high",
    status: "proposal_sent",
    notes: "Had excellent discovery call. Very motivated to move fast. Budget ~€8k-12k.",
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: "l2",
    userId: "user1",
    businessName: "GreenLeaf Consulting",
    contactName: "Mark Johnson",
    niche: "Sustainability",
    source: "Referral",
    painPoint: "Manual reporting processes eating up 40% of analyst time.",
    urgency: "medium",
    budgetSignal: "medium",
    status: "qualified",
    notes: "Referred by existing client. Wants dashboard + automated reports.",
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "l3",
    userId: "user1",
    businessName: "UrbanFit Gym Chain",
    contactName: "Lisa Park",
    niche: "Fitness",
    source: "Cold outreach",
    painPoint: "Member retention tracking is done in spreadsheets.",
    urgency: "low",
    budgetSignal: "low",
    status: "new",
    notes: "Initial contact made. Scheduled call for next week.",
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: "l4",
    userId: "user1",
    businessName: "BrightPath Education",
    contactName: "David Kim",
    niche: "EdTech",
    source: "Upwork",
    painPoint: "Need a student progress tracking portal for parents.",
    urgency: "high",
    budgetSignal: "medium",
    status: "new",
    notes: "Posted on Upwork 2 days ago. Strong requirements doc.",
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "l5",
    userId: "user1",
    businessName: "Coastal Realty",
    contactName: "Amanda Torres",
    niche: "Real Estate",
    source: "Website form",
    painPoint: "Property listing website is outdated and not mobile-friendly.",
    urgency: "medium",
    budgetSignal: "high",
    status: "won",
    notes: "Signed €6k contract for website rebuild. Starting next sprint.",
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "l6",
    userId: "user1",
    businessName: "TechBrew Coffee",
    contactName: "James Wright",
    niche: "Food & Beverage",
    source: "LinkedIn",
    painPoint: "Loyalty program is paper-based.",
    urgency: "low",
    budgetSignal: "low",
    status: "lost",
    notes: "Decided to go with a SaaS solution instead of custom build.",
    createdAt: Date.now() - 86400000 * 45,
    updatedAt: Date.now() - 86400000 * 20,
  },
];

export const mockProposals: Proposal[] = [
  {
    id: "pr1",
    userId: "user1",
    leadId: "l1",
    title: "Patient Intake & Progress Portal",
    status: "sent",
    problemSummary: "Acme Wellness lacks digital patient management. Clients book via phone, records are paper-based, and there's no way to track progress over time. This causes lost appointments, inconsistent client experiences, and inability to scale.",
    scope: "Custom web portal with patient intake forms, appointment scheduling, progress tracking dashboards, and therapist notes system. Mobile-responsive design. Integration with existing calendar tools.",
    deliverables: [
      "Patient intake form with validation",
      "Appointment scheduling system",
      "Therapist notes and session logging",
      "Patient progress dashboard",
      "Admin dashboard for business owner",
      "Mobile-responsive design",
    ],
    timeline: "6 weeks: Week 1-2 Design & Setup, Week 3-4 Core Build, Week 5 Testing, Week 6 Launch & Training",
    pricing: "€9,500 fixed price. 40% upfront, 40% at beta delivery, 20% at launch. Includes 30-day post-launch support.",
    assumptions: "Client provides branding assets by Week 1. Therapist staff available for 2 user testing sessions. No more than 3 revision rounds per milestone.",
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "pr2",
    userId: "user1",
    leadId: "l5",
    title: "Coastal Realty Website Rebuild",
    status: "accepted",
    problemSummary: "Current website is outdated, not mobile-responsive, and fails to convert visitors into leads. Competitors in the market have significantly better online presence.",
    scope: "Full website rebuild with modern design, property listing system with search/filter, contact forms, and SEO optimization.",
    deliverables: [
      "Modern responsive website design",
      "Property listing system with filters",
      "Individual property detail pages",
      "Lead capture forms",
      "SEO optimization",
      "CMS for content management",
    ],
    timeline: "4 weeks: Week 1 Design, Week 2-3 Build, Week 4 Launch",
    pricing: "€6,000 fixed price. 50% upfront, 50% at launch. Includes 14-day post-launch support.",
    assumptions: "Client provides all property photos and descriptions. Domain and hosting already available.",
    createdAt: Date.now() - 86400000 * 25,
    updatedAt: Date.now() - 86400000 * 10,
  },
];

export const mockServiceTemplates: ServiceTemplate[] = [
  {
    id: "st1",
    userId: "user1",
    name: "Landing Page + CRM Integration",
    description: "High-conversion landing page with lead capture, email automation, and CRM integration.",
    basePrice: "€2,500",
    deliverables: ["Custom landing page", "Lead capture form", "Email automation setup", "CRM integration", "Analytics setup"],
    estimatedDays: 7,
    category: "Web Development",
    createdAt: Date.now() - 86400000 * 60,
    updatedAt: Date.now() - 86400000 * 10,
  },
  {
    id: "st2",
    userId: "user1",
    name: "Full-Stack Web Application",
    description: "Custom web application with authentication, database, admin panel, and user-facing frontend.",
    basePrice: "€8,000",
    deliverables: ["User authentication", "Database design", "Admin dashboard", "User-facing UI", "API development", "Deployment"],
    estimatedDays: 30,
    category: "Web Application",
    createdAt: Date.now() - 86400000 * 50,
    updatedAt: Date.now() - 86400000 * 15,
  },
  {
    id: "st3",
    userId: "user1",
    name: "Technical Audit & Roadmap",
    description: "Comprehensive review of existing codebase, architecture, and recommendations for improvement.",
    basePrice: "€1,500",
    deliverables: ["Codebase review", "Architecture assessment", "Performance audit", "Security review", "Improvement roadmap"],
    estimatedDays: 5,
    category: "Consulting",
    createdAt: Date.now() - 86400000 * 40,
    updatedAt: Date.now() - 86400000 * 20,
  },
  {
    id: "st4",
    userId: "user1",
    name: "Dashboard & Reporting Tool",
    description: "Data visualization dashboard with charts, filters, exports, and automated report generation.",
    basePrice: "€5,000",
    deliverables: ["Dashboard design", "Chart components", "Data filtering", "Export functionality", "Automated reports"],
    estimatedDays: 14,
    category: "Web Application",
    createdAt: Date.now() - 86400000 * 35,
    updatedAt: Date.now() - 86400000 * 12,
  },
];

export const pipelineSummary = {
  new: mockLeads.filter((l) => l.status === "new").length,
  qualified: mockLeads.filter((l) => l.status === "qualified").length,
  proposalSent: mockLeads.filter((l) => l.status === "proposal_sent").length,
  won: mockLeads.filter((l) => l.status === "won").length,
  lost: mockLeads.filter((l) => l.status === "lost").length,
};
