import type { LearningItem, WeakSpot, StudySprint } from "@/types";

export const mockWeakSpots: WeakSpot[] = [
  {
    id: "ws1",
    userId: "user1",
    topic: "Auth flow edge cases",
    severity: "high",
    lastEncountered: Date.now() - 86400000 * 2,
    notes: "Struggled with token refresh logic and silent re-auth in Next.js middleware.",
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "ws2",
    userId: "user1",
    topic: "Complex Zod union types",
    severity: "medium",
    lastEncountered: Date.now() - 86400000 * 5,
    notes: "Discriminated unions with nested optional fields cause confusing type errors.",
    createdAt: Date.now() - 86400000 * 15,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "ws3",
    userId: "user1",
    topic: "CSS Grid complex layouts",
    severity: "low",
    lastEncountered: Date.now() - 86400000 * 12,
    notes: "Subgrid and auto-fill/auto-fit still unintuitive.",
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 12,
  },
  {
    id: "ws4",
    userId: "user1",
    topic: "Firestore compound queries",
    severity: "medium",
    lastEncountered: Date.now() - 86400000 * 3,
    notes: "Composite index requirements and limitations on inequality filters.",
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 3,
  },
];

export const mockStudySprint: StudySprint = {
  id: "ss1",
  userId: "user1",
  title: "Firebase Security Rules Mastery",
  goal: "Understand role-based query constraints, field-level rules, and custom claims for multi-tenancy patterns.",
  topic: "Firebase Security",
  durationDays: 14,
  progress: 40,
  status: "active",
  createdAt: Date.now() - 86400000 * 7,
  updatedAt: Date.now() - 86400000,
};

export const mockRecommendedTopics = [
  { id: "rt1", title: "Next.js Server Actions", reason: "Used in your current project stack" },
  { id: "rt2", title: "React Server Components", reason: "Upcoming pattern in Next.js architecture" },
  { id: "rt3", title: "Value-Based Pricing", reason: "Improves your freelance revenue" },
  { id: "rt4", title: "System Design Patterns", reason: "Strengthens architecture decisions" },
  { id: "rt5", title: "AI Prompt Engineering", reason: "Core to your Mission Control workflows" },
];

export const mockLearningItems: LearningItem[] = [
  {
    id: "li1",
    userId: "user1",
    title: "Advanced Firebase Security Rules",
    category: "Backend",
    skillLevel: "intermediate",
    status: "in_progress",
    progress: 65,
    notes: "Focus on request.auth and resource.data patterns",
    tags: ["firebase", "security", "backend"],
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now() - 86400000,
  },
  {
    id: "li2",
    userId: "user1",
    title: "TypeScript Generics Deep Dive",
    category: "Language",
    skillLevel: "advanced",
    status: "in_progress",
    progress: 40,
    tags: ["typescript", "generics", "types"],
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now() - 86400000 * 2,
  },
  {
    id: "li3",
    userId: "user1",
    title: "Freelance Discovery Calls",
    category: "Business",
    skillLevel: "beginner",
    status: "in_progress",
    progress: 30,
    tags: ["freelance", "sales", "communication"],
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now() - 86400000 * 3,
  },
  {
    id: "li4",
    userId: "user1",
    title: "React Testing with Vitest",
    category: "Testing",
    skillLevel: "beginner",
    status: "not_started",
    progress: 0,
    tags: ["testing", "react", "vitest"],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now() - 86400000 * 5,
  },
  {
    id: "li5",
    userId: "user1",
    title: "Tailwind CSS Advanced Patterns",
    category: "Frontend",
    skillLevel: "intermediate",
    status: "completed",
    progress: 100,
    tags: ["css", "tailwind", "design"],
    createdAt: Date.now() - 86400000 * 30,
    updatedAt: Date.now() - 86400000 * 7,
  },
  {
    id: "li6",
    userId: "user1",
    title: "Cloud Functions Best Practices",
    category: "Backend",
    skillLevel: "intermediate",
    status: "review",
    progress: 90,
    tags: ["firebase", "functions", "serverless"],
    createdAt: Date.now() - 86400000 * 20,
    updatedAt: Date.now() - 86400000 * 4,
  },
];
